// Starlit Pulse style: every track has an unmistakable genre, theme, arrangement identity, and original lyric arc.
export type Genre = "NEO SOUL" | "CITY POP" | "BOOM BAP" | "POST ROCK" | "FRENCH HOUSE" | "AMBIENT" | "DRUM'N'BASS" | "COUNTRY FOLK" | "NEOCLASSICAL" | "TRAP" | "JAZZ FUSION" | "CHILLHOP" | "SAMBA" | "HARD TECHNO" | "CHAMBER MUSIC" | "BLUES ROCK" | "AMERICANA" | "SYNTHWAVE" | "SWING" | "DOWNTEMPO" | "GRIME" | "K-POP" | "GOTHIC WALTZ" | "BOSSA NOVA" | "FUTURE BASS" | "GARAGE ROCK" | "LATIN JAZZ" | "HYPERPOP" | "BLUEGRASS" | "CINEMATIC";
export type LyricCue = { at: number; text: string };
export type Track = { id: number; title: string; artist: string; bpm: number; key: number; mood: string; color: string; genre: Genre; instrument: string; audioUrl: string; lyrics: LyricCue[] };
export type Character = { id: number; name: string; role: string; imageUrl: string; accent: string };
export const characters: Character[] = [
  { id: 1, name: "LUMA", role: "VOCAL / SYNTH", imageUrl: "/manus-storage/neon-beat-star-character-01_3d051c2e.png", accent: "#A8F0EE" },
  { id: 2, name: "RIFT", role: "ELECTRIC GUITAR", imageUrl: "/manus-storage/neon-beat-star-character-02_04a123d4.png", accent: "#C7B7FF" },
  { id: 3, name: "MIRA", role: "DJ / BEAT MAKER", imageUrl: "/manus-storage/neon-beat-star-character-03_253f2ee1.png", accent: "#FFB9C8" },
  { id: 4, name: "NOA", role: "VIOLIN / CLASSICAL", imageUrl: "/manus-storage/neon-beat-star-character-04_66f703bc.png", accent: "#FFE9A8" },
  { id: 5, name: "KAI", role: "RAP / STREET", imageUrl: "/manus-storage/neon-beat-star-character-05_c4c788f0.png", accent: "#FF7EEA" },
];

type Entry = Omit<Track, "id" | "audioUrl" | "lyrics"> & { lyrics: string[] };
const entries: Entry[] = [
  { title: "Afterglow Avenue", artist: "Lumen Arc", bpm: 92, key: 0, mood: "DAWN", color: "#A8F0EE", genre: "NEO SOUL", instrument: "Rhodes · Muted Guitar · Pocket Drums", lyrics: ["鏡の奥で眠る名前を　誰にも渡さず抱えていた", "赦せない昨日を磨くほど　指先に自分の傷が残る", "愛されるための形を捨て　欠けたままの輪郭で立つ", "夜明けは始まりではなく　選び直した私の証明"] },
  { title: "Signal Bloom", artist: "Mira/01", bpm: 112, key: 2, mood: "RAIN", color: "#C7B7FF", genre: "CITY POP", instrument: "Juno Synth · Chorus Guitar · Linn Drums", lyrics: ["雨上がりの交差点で　失くした声の続きを探す", "古いカセットの沈黙には　言えなかった別れが眠る", "きれいな記憶だけを残すと　君の痛みまで消えてしまう", "濡れたネオンを踏み越えて　名前のない明日を呼びに行く"] },
  { title: "Coral Static", artist: "Vanta Kids", bpm: 96, key: 1, mood: "STREET", color: "#FFB9C8", genre: "BOOM BAP", instrument: "Dusty Sampler · Upright Bass · Vinyl Drums", lyrics: ["路地裏の地図に残った線は　逃げた日々の数ではない", "負けを韻に変えるたび　誰かの正しさが遠ざかる", "怒りを手放せば楽になる　それでも声まで捨てたくない", "錆びた街の片隅から　自分の値段を自分で書き直す"] },
  { title: "Midnight Vector", artist: "Nocturne Lab", bpm: 128, key: 3, mood: "ASCENT", color: "#FFE9A8", genre: "POST ROCK", instrument: "Baritone Guitar · Live Drums · Delay Pedals", lyrics: ["切れた衛星の信号を　孤独の塔から拾い上げる", "遠い誰かの沈黙にも　届かなかった祈りがある", "崩れるほど積んだ壁は　守るものと閉じ込めるものを分けた", "最後のノイズを越え　返事のない空へなお送信する"] },
  { title: "Starboard", artist: "KAIRO", bpm: 124, key: 0, mood: "GLOW", color: "#A8F0EE", genre: "FRENCH HOUSE", instrument: "Talkbox Bass · Filtered Piano · Four-on-floor", lyrics: ["鏡のボールが回るたび　昨日の肩書きが剥がれていく", "踊る輪の外にいる人を　見ないふりで救った気にならない", "胸の小さな火を重ね　誰かの夜にも灯りを分ける", "自由は逃げ道ではなく　互いの違いを抱くための音"] },
  { title: "Glass Horizon", artist: "ECHO SODA", bpm: 68, key: 2, mood: "DEEP", color: "#C7B7FF", genre: "AMBIENT", instrument: "Granular Pad · Glass Chimes · Sub Drone", lyrics: ["深海の呼吸を数え　言葉になる前の痛みに触れる", "光の届かない場所にも　見捨てられない青がある", "急がなくていいと言う声が　諦めとどう違うのか考えた", "浮上する私の手には　沈んだ時間を抱く余白がある"] },
  { title: "Pulse Theory", artist: "NEON UNIT", bpm: 174, key: 1, mood: "RUSH", color: "#FFB9C8", genre: "DRUM'N'BASS", instrument: "Reese Bass · Breakbeats · Bright Reese Lead", lyrics: ["高速鉄道の窓に　未来の街が過去のように流れる", "秒針より速い鼓動で　置き去りにした人を思い出す", "分岐するレールの先で　勝つことより戻る道を選ぶ", "加速の果てに間に合うのは　誰かと呼吸を合わせた時だけ"] },
  { title: "Sundial", artist: "Aster/Y", bpm: 104, key: 3, mood: "HOMEBOUND", color: "#FFE9A8", genre: "COUNTRY FOLK", instrument: "Fingerpicked Guitar · Banjo · Fiddle", lyrics: ["古いポストの手紙には　帰れなかった季節の匂いがする", "母の声を遠ざけたのは　自由ではなく怖さだった", "山道の風は責めずに　変わった私の名を呼び直す", "帰るとは負けではなく　置き去りにした自分を迎えること"] },
  { title: "Blue Comet", artist: "ORBITAL", bpm: 116, key: 0, mood: "SKY", color: "#A8F0EE", genre: "NEOCLASSICAL", instrument: "Prepared Piano · String Quartet · Celesta", lyrics: ["冬の天文台で　止まった時計に未来を問いかける", "星は過去の光なのに　今の傷を正確に照らしていた", "失った時間を埋めるためでなく　空白ごと旋律に置く", "青い彗星の尾を追い　遅れた人生にも軌道を与える"] },
  { title: "Night Bus", artist: "KASA", bpm: 140, key: 1, mood: "RESTART", color: "#FFB9C8", genre: "TRAP", instrument: "808 Sub · Triplet Hats · Dark Bell", lyrics: ["終電の窓に映る顔を　他人の失敗のように笑った", "底まで落ちた夜には　蹴り上げる床さえ借り物だった", "傷を隠すフードを脱ぎ　助けを求める声を恥じない", "ゼロから数える強さは　ひとりで立つことではない"] },
  { title: "Prism Runner", artist: "SPECTRA", bpm: 136, key: 2, mood: "CHROMA", color: "#C7B7FF", genre: "JAZZ FUSION", instrument: "Electric Piano · Soprano Sax · Odd-meter Drums", lyrics: ["プリズムの中を走る色は　決められた答えを拒んで変わる", "間違ったコードにも　生き延びた身体の履歴がある", "即興は才能ではなく　崩れた瞬間を聴き続ける覚悟", "光そのものにならず　光を分ける人として次の小節へ"] },
  { title: "Low Gravity", artist: "MELT", bpm: 82, key: 3, mood: "FLOAT", color: "#FFE9A8", genre: "CHILLHOP", instrument: "Wurlitzer · Dusty Drums · Tape Flutter", lyrics: ["眠れない部屋の隅で　時計だけが海を泳いでいる", "冷めたコーヒーの輪に　言い訳と明日の形を描いた", "答えを急ぐほど　誰かの痛みを背景にしてしまう", "重力を忘れるのではなく　重いものと一緒に呼吸する"] },
  { title: "Satellite Kiss", artist: "LIAISON", bpm: 118, key: 0, mood: "SUMMER", color: "#A8F0EE", genre: "SAMBA", instrument: "Cavaquinho · Surdo · Brass Section", lyrics: ["遠い衛星のキスが　祝祭の太鼓を越えて届いた", "波打つリズムの向こう　離れて暮らす家族を思い出す", "距離は消えなくても　踊る足元から道を作れる", "同じ砂を踏めなくても　同じ月を選ぶ夜は残る"] },
  { title: "Zero Hour", artist: "DARKROOM", bpm: 148, key: 1, mood: "REBELLION", color: "#FFB9C8", genre: "HARD TECHNO", instrument: "Industrial Kick · Acid Bass · Metallic Percussion", lyrics: ["零時の工場で　機械の心臓が命令を待っていた", "赤いスイッチを押す手には　奪われた名前の重さがある", "壊すことだけを自由と呼べば　次の檻を作ってしまう", "反抗は冷たい火　誰も捨てない回路を開くために燃える"] },
  { title: "Rain on Glass", artist: "NAMI", bpm: 88, key: 2, mood: "MEMORY", color: "#C7B7FF", genre: "CHAMBER MUSIC", instrument: "Piano Trio · Viola · Bass Clarinet", lyrics: ["祖母の時計は　雨の譜面を静かに刻み続ける", "受け継いだ沈黙の中に　守られた秘密と傷ついた秘密がある", "過去を美談にしないまま　今日の私が続きを選ぶ", "世代を越える小節は　忘れないことと縛られないこと"] },
  { title: "Sunset Driver", artist: "MOTION FWD", bpm: 130, key: 3, mood: "OPEN ROAD", color: "#FFE9A8", genre: "BLUES ROCK", instrument: "Overdriven Guitar · Hammond Organ · Live Kit", lyrics: ["失恋の跡をミラーに　夕焼けが何度も塗り替える", "折れたピックを捨てても　言えなかった言葉は助手席にいる", "痛みを燃料にすれば　誰かを追い越すだけの旅になる", "地平線へ走るのは　戻れない自分を許すため"] },
  { title: "Lighthouse", artist: "TIDE CODE", bpm: 98, key: 0, mood: "SOLITUDE", color: "#A8F0EE", genre: "AMERICANA", instrument: "Pedal Steel · Acoustic Guitar · Harmonica", lyrics: ["灯台守の窓から　帰らない船の数を数えていた", "誰かを照らす役目に隠れ　自分の暗がりを見ないでいた", "届かない海へ火を送る　それでも孤独を美化しない", "霧が晴れる朝には　照らされる側へ戻る道も残す"] },
  { title: "Electric Garden", artist: "BOTANICA", bpm: 118, key: 2, mood: "NOSTALGIC", color: "#C7B7FF", genre: "SYNTHWAVE", instrument: "Analog Arp · Linn Snare · Chorus Bass", lyrics: ["架空の八十年代へ　父の若い笑顔を探しに行った", "過去を借りるたび　知らなかった後悔まで背負ってしまう", "懐かしさは逃げ道ではなく　失われた会話を始める入口", "電気の花を摘み　借り物でない未来の色を選ぶ"] },
  { title: "Afterimage", artist: "YUKI/FRAME", bpm: 132, key: 1, mood: "MASKED", color: "#FFB9C8", genre: "SWING", instrument: "Big Band Brass · Upright Bass · Piano Comping", lyrics: ["仮面舞踏会の角で　笑顔の裏の本名を隠していた", "見抜かれないことを愛と呼び　近づく人を試していた", "踊りの一歩を止めれば　相手の沈黙も聴こえてくる", "朝が来るまでに　赦しを求める順番を間違えない"] },
  { title: "Paper Moon", artist: "SOFT SIGNAL", bpm: 78, key: 3, mood: "INNER SPACE", color: "#FFE9A8", genre: "DOWNTEMPO", instrument: "Sub Bass · Felt Piano · Textured Percussion", lyrics: ["砂漠の夜は広すぎて　問いだけが星へ散っていく", "乾いた風の向こうに　自分で選ばなかった人生がある", "答えを掘り当てるより　影を連れたまま歩く方を選ぶ", "紙の月は偽物でも　暗がりを見つめる目は本物だ"] },
  { title: "Skyline Echo", artist: "CITYMUTE", bpm: 142, key: 0, mood: "BOUNDARY", color: "#A8F0EE", genre: "GRIME", instrument: "Square Bass · Sparse Drums · Angular Synth", lyrics: ["境界線の上で　借り物の言葉を一つずつ返していく", "若い声が重なるほど　壁の向こうの恐れも近くなる", "勝つために尖るだけでは　隣の傷を見落としてしまう", "ここにいる証明を　誰かを消さない形で街へ残す"] },
  { title: "Candy Voltage", artist: "POP CIRCUIT", bpm: 128, key: 2, mood: "TOGETHER", color: "#C7B7FF", genre: "K-POP", instrument: "Gloss Synth · Tight Bass · Layered Claps", lyrics: ["ひとりで描いた夢に　違う色の手が触れていく", "同じサビを歌うために　消したくなる違いも抱えた", "失敗した振り付けを笑う時　弱さを安全に置ける場所ができる", "仲間とは同じになることではなく　違うまま帰れること"] },
  { title: "Black Halo", artist: "RIFT", bpm: 150, key: 1, mood: "FORGIVENESS", color: "#FFB9C8", genre: "GOTHIC WALTZ", instrument: "Pipe Organ · Low Strings · Timpani", lyrics: ["月影の城で　許されない手紙を何度も燃やした", "罪の重さを測る鐘は　被害者の時間を返してはくれない", "赦しを求める言葉を　自分を軽くする道具にしない", "黒い輪の内側で　責任を抱えたまま静かな芽を守る"] },
  { title: "Static Rain", artist: "WAVEFORM", bpm: 108, key: 3, mood: "FAREWELL", color: "#FFE9A8", genre: "BOSSA NOVA", instrument: "Nylon Guitar · Soft Percussion · Flute", lyrics: ["窓辺の午後に　別れの予感が薄く漂っていた", "冷めたカップの縁をなぞる指に　言わない選択の重さがある", "さよならを急がず　相手の未来を自分の物語にしない", "歩き出す背中へ　戻れないことではなく続けられることを送る"] },
  { title: "Velvet Orbit", artist: "MORPH", bpm: 128, key: 0, mood: "SIGNAL", color: "#A8F0EE", genre: "FUTURE BASS", instrument: "Sidechain Pads · Vocal Chops · Wide Sub", lyrics: ["空中都市の窓から　恋の信号を何度も送っている", "返信のない光を希望と呼ぶ前に　沈黙の意思も受け取る", "軌道を変えるほど強く　それでも相手の空を奪わずに", "届くとは所有ではなく　離れたまま同じ夜を選ぶこと"] },
  { title: "Firefly Code", artist: "KODAMA", bpm: 136, key: 2, mood: "YOUTH", color: "#C7B7FF", genre: "GARAGE ROCK", instrument: "Fuzz Guitar · Live Bass · Snare Cracks", lyrics: ["反射する窓に　昨日の青春がまだ爆発している", "壊れたアンプから　怒りと恥ずかしさが同じ音で鳴る", "正しさを急いで叫ぶほど　聞きたかった声を遠ざけた", "蛍のような一瞬を　傷つけない記憶として残していく"] },
  { title: "Parallel Hearts", artist: "DUO", bpm: 124, key: 1, mood: "PORT", color: "#FFB9C8", genre: "LATIN JAZZ", instrument: "Piano Montuno · Congas · Flugelhorn", lyrics: ["港町の記憶が　潮の匂いで帰ってくる", "違う船に乗ったふたりは　同じ月を見ても同じ場所へ着かない", "踊りの途中でだけ　言葉より近くなれる夜がある", "結び直すのは関係ではなく　別々の人生を祝うための距離"] },
  { title: "Moonlit Arcade", artist: "PIXEL FOG", bpm: 160, key: 3, mood: "DIGITAL BIRTH", color: "#FFE9A8", genre: "HYPERPOP", instrument: "Bitcrushed Synth · Glitch Drums · Elastic Bass", lyrics: ["デジタルの人格が　初めて自分の影を見つけた", "削除された記憶にも　選ばれなかった痛みが残っている", "誰かのコピーでない証明を　完璧さではなく迷いに置く", "新しい名前でログインし　作られた私が作る未来を始める"] },
  { title: "Daybreak 404", artist: "NULL/SUN", bpm: 116, key: 0, mood: "HOMECOMING", color: "#A8F0EE", genre: "BLUEGRASS", instrument: "Banjo · Mandolin · Upright Bass · Fiddle", lyrics: ["山道の分かれ目で　仲間の笑い声を思い出した", "遠回りしたブーツにも　逃げた日々の土がよく似合う", "帰郷は後退ではなく　変わった自分で根を確かめる旅", "谷間に響く五つの弦が　ただいまを誰かの明日へ渡す"] },
  { title: "One More Star", artist: "NEON BEAT STAR", bpm: 144, key: 2, mood: "FINAL JOURNEY", color: "#FFB9C8", genre: "CINEMATIC", instrument: "String Orchestra · French Horn · Taiko", lyrics: ["最後の星へ向かう船で　地球が窓の外に小さくなる", "ここまでの夜を美談にせず　失ったものの名前も航路に刻む", "別れではなく続きを選ぶ　その選択が誰かを置き去りにしないように", "もう一つ星を鳴らし　帰れる朝を互いの手で照らしに行く"] },
];

export const tracks: Track[] = entries.map((entry, index) => ({
  ...entry,
  id: index + 1,
  audioUrl: `/assets/track-${String(index + 1).padStart(2, "0")}.mp3`,
  lyrics: entry.lyrics.map((text, lyricIndex) => ({ at: [5, 14, 24, 35][lyricIndex], text })),
}));
